apiVersion: v1
kind: Service
metadata:
  name: service-1
  labels:
    app: acuario-pablo
spec:
  selector:
    app: acuario-pablo
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
